Areas/Admin/Pages/User/EditUserRoleClaim.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Azure;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VTT.models;

namespace App.Admin.User
{
    public class EditUserRoleClaimModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public EditUserRoleClaimModel(AppDbContext myBlogContext, UserManager<AppUser> userManager)
        {
            _context = myBlogContext;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }
        public NotFoundObjectResult OnGet() => NotFound("Không được truy cập");

        public class InputModel 
        {
            [Display(Name = "Kiểu (tên) claim")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} ký tự")]
            public string ClaimType { get; set; }

            [Display(Name = "Giá trị")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} ký tự")]
            public string ClaimValue { get; set; }            
        }

        [BindProperty]
        public InputModel Input {set; get;}
        
        public AppUser user { get; set; }

        public async Task<IActionResult> OnGetAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);
            if (user == null) return NotFound("Không tìm thấy user");
            return Page();
        }
        public async Task<IActionResult> OnPostAddClaimAsync(string userid)
        {
            user = await _userManager.FindByIdAsync(userid);
            if (user == null) return NotFound("Không tìm thấy user");

            if (!ModelState.IsValid) return Page();
            var claims = _context.UserClaims.Where(c => c.UserId == user.Id);

            if (claims.Any(c => c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue))
            {
                ModelState.AddModelError(string.Empty, "Đặc tính này đã có");
                return Page();
            }

            await _userManager.AddClaimAsync(user, new Claim(Input.ClaimType, Input.ClaimValue));
            StatusMessage = "Đã thêm đặc tính cho user";
            return RedirectToPage("./AddRole", new {Id = user.Id});
        }

        public IdentityUserClaim<string> userclaim { get; set; }
        
        public async Task<IActionResult> OnGetEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy user");

            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            user = await _userManager.FindByIdAsync(userclaim.UserId);

            if (user == null) return NotFound("Không tìm thấy user");

            Input = new InputModel()
            {
                ClaimType = userclaim.ClaimType,
                ClaimValue = userclaim.ClaimValue

            };

            return Page();
        }
        public async Task<IActionResult> OnPostEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy user");

            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            user = await _userManager.FindByIdAsync(userclaim.UserId);

            if (user == null) return NotFound("Không tìm thấy user");

            if (!ModelState.IsValid) return Page();

            if (_context.UserClaims.Any(c => c.UserId == user.Id 
                && c.ClaimType == Input.ClaimType 
                && c.ClaimValue == Input.ClaimValue 
                && c.Id != userclaim.Id))
                {
                    ModelState.AddModelError(string.Empty, "Claim này đã có");
                    return Page();
                }


            userclaim.ClaimType = Input.ClaimType;
            userclaim.ClaimValue = Input.ClaimValue;

            await _context.SaveChangesAsync();
            StatusMessage = "Bạn vừa cập nhật claim";
            
            return RedirectToPage("./AddRole", new {Id = user.Id});
        } 

        public async Task<IActionResult> OnPostDeleteAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy user");

            userclaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            user = await _userManager.FindByIdAsync(userclaim.UserId);

            if (user == null) return NotFound("Không tìm thấy user");

            await _userManager.RemoveClaimAsync(user, new Claim(userclaim.ClaimType, userclaim.ClaimValue));

            StatusMessage = "Bạn đã xóa claim";
            
            return RedirectToPage("./AddRole", new {Id = user.Id});
        } 
    
    }
}

Areas/Admin/Pages/User/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using VTT.models;

namespace App.Admin.User
{

    // [Authorize] 
    public class IndexModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        public IndexModel(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public class UserAndRole : AppUser
        {
            public string RoleNames { get; set; }
        }
        public List<UserAndRole> users  {set; get;}

        public const int ITEMS_PER_PAGE = 10;

        [BindProperty(SupportsGet = true, Name = "p")]
        public int currentPage { get; set; }

        public int countPages { get; set; }

        public int totalUsers { get; set; }

        public async Task OnGet()
        {
            // users =  await _userManager.Users.OrderBy(u => u.UserName).ToListAsync();
            var qr = _userManager.Users.OrderBy(u => u.UserName);

            totalUsers = await qr.CountAsync();
            countPages = (int)Math.Ceiling((double)totalUsers / ITEMS_PER_PAGE);

            if (currentPage < 1)
                currentPage = 1;
            if (currentPage > countPages)
                currentPage = countPages;

            var qr1 = qr.Skip((currentPage - 1) * ITEMS_PER_PAGE)
                        .Take(ITEMS_PER_PAGE)
                        .Select(u => new UserAndRole() {
                            Id = u.Id,
                            UserName = u.UserName,
                        });

            users = await qr1.ToListAsync();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.RoleNames = string.Join(",", roles);
            }

        }

        public void OnPost() => RedirectToPage();
    }
}

Areas/Admin/Pages/User/SetPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VTT.models;

namespace App.Admin.User
{
    public class SetPasswordModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SetPasswordModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public class InputModel
        {
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(100, ErrorMessage = "{0} phải dài {2} đến {1} ký tự.", MinimumLength = 3)]
            [DataType(DataType.Password)]
            [Display(Name = "Mật khẩu mới")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Xác nhận mật khẩu")]
            [Compare("NewPassword", ErrorMessage = "Lặp lại mật khẩu không chính xác.")]
            public string ConfirmPassword { get; set; }
        }

        public AppUser user { get; set; }
        
        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound($"Không có user");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound($"Không thấy user, id = {id}.");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound($"Không có user");
            }

            user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound($"Không thấy user, id = {id}.");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }
             
            await _userManager.RemovePasswordAsync(user);

            var addPasswordResult = await _userManager.AddPasswordAsync(user, Input.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                foreach (var error in addPasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            StatusMessage = $"Vừa cập nhật mật khẩu cho user: {user.UserName}";

            return RedirectToPage("./Index");
        }
    }

}

Areas/Admin/Pages/User/AddRole.cshtml
@page "/admin/assign-user-role/{id}"
@model App.Admin.User.AddRoleModel
@{
    ViewData["Title"] = "Gán role";
}

<h4>Thiết lập role cho user: @Model.user.UserName</h4>
<partial name="_StatusMessage" for="StatusMessage" />

@{
    
   
}
<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="RoleNames"></label>
                @Html.ListBoxFor(m => m.RoleNames, @Model.allRoles, new {
                    id = "id-select-roles",
                    @class = "w-100"
                })
                <span asp-validation-for="RoleNames" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Cập nhật</button>
            <a class="btn btn-primary" asp-page="./Index">Danh sách thành viên</a>
        </form>
        <hr>
        <p>Các claim của user có được từ role:</p>
        @if (Model.claimsInRole.Count >  0)
        {
            <ul>
                @foreach (var claim in Model.claimsInRole)
                {
                    <li>@claim.ClaimType : @claim.ClaimValue</li>
                }
            </ul>
        }
        <p>Các claim riêng:
            <a asp-page="./EditUserRoleClaim" asp-page-handler="AddClaim" asp-route-userid="@Model.user.Id">+ Thêm claim riêng</a>     
        </p>
        @if (Model.claimsInUserClaim.Count >  0)
        {
            <ul>
                @foreach (var claim in Model.claimsInUserClaim)
                {
                    <li>
                        <a asp-page="./EditUserRoleClaim" asp-page-handler="EditClaim" asp-route-claimid="@claim.Id">@claim.ClaimType : @claim.ClaimValue</a>
                    </li>
                }
            </ul>
        }




    </div>
</div>


@section Scripts {

    <script src="~/lib/multi-select/js/jquery.multi-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multi-select/css/multi-select.min.css" />

    <script>
        $("#id-select-roles").multipleSelect({
            selectAll: false,
            keepOpen: false,
            isOpen: false,
        });
    </script>

    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Pages/User/EditUserRoleClaim.cshtml
@page "/admin/edit-user-claim/{userid?}"
@model App.Admin.User.EditUserRoleClaimModel
@{
    ViewData["Title"] = "Claim của user";
}
<h1>@ViewData["Title"] : @Model.user.UserName</h1>
<partial name="_StatusMessage" for="StatusMessage" />


<hr>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Input.ClaimType" class="control-label"></label>
                <input asp-for="Input.ClaimType" class="form-control" />
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.ClaimValue" class="control-label"></label>
                <input asp-for="Input.ClaimValue" class="form-control" />
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                @if (Model.userclaim != null)
                {
                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    <input type="submit" value="Xóa" asp-route-claimid="@Model.userclaim.Id" class="btn btn-danger" asp-page-handler="Delete" />
                }
                else 
                {
                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                }
                

                <a class="btn btn-primary" asp-page="./AddRole" asp-route-id="@Model.user.Id">Edit User</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Pages/User/Index.cshtml
@page "/admin/members"
@model App.Admin.User.IndexModel
@{
    ViewData["Title"] = "Danh sách các thành viên";
}
<h2>@ViewData["Title"]</h2>
<partial name="_StatusMessage" model="@Model.StatusMessage"></partial>
<p>Tổng số thành viên: @Model.totalUsers</p>
<a class="btn btn-secondary"asp-page="../Role/Index">Quản lý role</a>


<table class="table">
    <tr>
        <th>Tên user</th>
        <th>Vai trò (role)</th>
        <th>Tác vụ</th>
    </tr>
    @foreach (var user in Model.users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>
                @if (string.IsNullOrEmpty(user.RoleNames))
                {
                    <a class="text-dark" asp-page="./AddRole" asp-route-id="@user.Id">+ Thêm roles</a>
                }
                else
                {
                    <a asp-page="./AddRole" asp-route-id="@user.Id">@user.RoleNames</a>
                }
            </td>
            <td>
                <a class="btn btn-success btn-sm" asp-page="./SetPassword" asp-route-id="@user.Id">Đặt mật khẩu</a>
            </td>
        </tr>
    }
</table>
@{
    var pagingmodel = new VTT.Helpers.PagingModel()
    {
        currentpage = Model.currentPage,
        countpage = Model.countPages,
        generateUrl = (int? p) => Url.Page("./Index", new { p = p})
    };
}

<partial name="_PagingXTL" model="@pagingmodel" />

Areas/Admin/Pages/User/SetPassword.cshtml
@page "/admin/set-member-password/{id}"
@model App.Admin.User.SetPasswordModel
@{
    ViewData["Title"] = "Đặt mật khẩu";
}

<h4>Thiết lập mật khẩu cho thành viên: @Model.user.UserName</h4>
<partial name="_StatusMessage" for="StatusMessage" />


<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.NewPassword"></label>
                <input asp-for="Input.NewPassword" class="form-control" />
                <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.ConfirmPassword"></label>
                <input asp-for="Input.ConfirmPassword" class="form-control" />
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="m-2">
                <button type="submit" class="btn btn-primary">Đặt mật khẩu</button>
                <a class="btn btn-primary" asp-page="./Index">Danh sách thành viên</a>

            </div>


        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Pages/User/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}